=== Soothsilver/NajdiCestuVen/Shared/Stories/Scenes/scene.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="scene" type="TScene">
    </xs:element>
    <xs:complexType name="TScene">
        <xs:all>
            <xs:element name="storage" minOccurs="0">
                <xs:complexType>
                    <xs:sequence minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="script" minOccurs="0" maxOccurs="unbounded">
                            <xs:complexType>
                                <xs:complexContent>
                                    <xs:extension base="TScript">
                                        <xs:attribute name="name" type="xs:string" />                                        
                                    </xs:extension>
                                </xs:complexContent>
                            </xs:complexType>
                        </xs:element>
                        <xs:element name="item" minOccurs="0" maxOccurs="unbounded">
                            <xs:complexType>
                                <xs:attribute name="art" type="art" use="required" />
                                <xs:attribute name="description" type="xs:string" use="required" />
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="minimapBase" type="art" minOccurs="0" />
            <xs:element name="minimap" type="art" minOccurs="0" />
            <xs:element name="scenes" minOccurs="0">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="scene" maxOccurs="unbounded">
                            <xs:complexType>
                                <xs:complexContent>
                                    <xs:extension base="TScene">
                                        <xs:attribute name="name" type="xs:string" />
                                    </xs:extension>
                                </xs:complexContent>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="backgrounds" type="arts" minOccurs="0" />
            <xs:element name="directions" minOccurs="0">
                <xs:complexType>
                    <xs:all>
                        <xs:element name="turnaround" type="TScript" minOccurs="0" />
                        <xs:element name="right" type="TScript" minOccurs="0" />
                        <xs:element name="left" type="TScript" minOccurs="0" />
                    </xs:all>
                </xs:complexType>
            </xs:element>
            <xs:element name="enter" type="TScript" minOccurs="0"/>
            <xs:element name="items" minOccurs="0">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="interactible" type="interactible" minOccurs="0" maxOccurs="unbounded" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:all>
        <xs:attribute name="type" type="xs:string" use="optional" />
        <xs:attribute name="escapeToTurnaround" use="optional">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="true" />
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>
    <xs:simpleType name="art">
        <xs:restriction base="xs:string" />
    </xs:simpleType>
    <xs:complexType name="arts">
        <xs:sequence>
            <xs:element name="art" type="art" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="interactible">
        <xs:sequence>
            <xs:element name="rectangle" type="xs:string" />
            <xs:element name="first" type="interaction" minOccurs="1" />
            <xs:element name="second" type="interaction" minOccurs="0" />
            <xs:element name="itemuse" minOccurs="0">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="failure" minOccurs="0" maxOccurs="1" type="TScript" />
                        <xs:element name="withItem" minOccurs="0" maxOccurs="unbounded">
                            <xs:complexType>
                                <xs:complexContent>
                                    <xs:extension base="TScript">
                                        <xs:attribute name="art" type="art" use="required" />
                                    </xs:extension>
                                </xs:complexContent>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                    <xs:attribute name="failure" type="xs:string" />
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required" />
        <xs:attribute name="art" type="art" />
    </xs:complexType>
    <xs:complexType name="interaction" >
        <xs:complexContent>
            <xs:extension base="TScript">
                <xs:attribute name="think" type="xs:string" /> 
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="TScript">
        <xs:sequence>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element name="goToRoom" type="xs:string"/>
                <xs:element name="think" type="xs:string" />
                <xs:element name="popScene">
                    <xs:complexType>
                    </xs:complexType>
                </xs:element>
                <xs:element name="addToInventory">
                    <xs:complexType>
                        <xs:attribute name="art" type="art" use="required" />
                        <xs:attribute name="description" type="xs:string" use="required" />
                    </xs:complexType>
                </xs:element>
                <xs:element name="destroyInteractible">
                    <xs:complexType>
                        <xs:attribute name="name" type="xs:string" use="required" />
                    </xs:complexType>
                </xs:element>
                <xs:element name="pushScene">
                    <xs:complexType>
                        <xs:attribute name="name" type="xs:string" use="required" />
                    </xs:complexType>
                </xs:element>
                <xs:element name="s">
                    <xs:complexType>
                        <xs:complexContent>
                            <xs:extension base="xs:integer">
                                <xs:attribute name="speaker" type="character" use="required" />
                                <xs:attribute name="pose" type="pose" />
                            </xs:extension>
                        </xs:complexContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="removeHeldItem">
                    <xs:complexType>                        
                    </xs:complexType>
                </xs:element>
                <xs:element name="setInteractibleFirstAndSecondUse">
                    <xs:complexType>
                        <xs:complexContent>
                            <xs:extension base="TScript">
                                <xs:attribute name="interactible" type="xs:string" use="required" />
                            </xs:extension>
                        </xs:complexContent>
                    </xs:complexType>
                </xs:element>

                <xs:element name="setInteractibleArt">
                    <xs:complexType>                        
                        <xs:attribute name="interactible" type="xs:string" use="required" />
                        <xs:attribute name="art" type="art" use="required" />
                    </xs:complexType>
                </xs:element>
                <xs:element name="setFlag">
                    <xs:complexType>
                        <xs:attribute name="flag" type="xs:string" use="required" />
                    </xs:complexType>
                </xs:element>
                <xs:element name="ifFlag">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="then" type="TScript" />
                            <xs:element name="else" type="TScript" />
                        </xs:sequence>
                        <xs:attribute name="flag" use="required" />
                    </xs:complexType>
                </xs:element>
                <xs:element name="removeBackgroundArt">
                    <xs:complexType>
                        <xs:attribute name="art" type="art" />
                    </xs:complexType>
                </xs:element>
                <xs:element name="addBackgroundArt">
                    <xs:complexType>
                        <xs:attribute name="art" type="art" />
                    </xs:complexType>
                </xs:element>
                <xs:element name="enqueue">
                    <xs:complexType>
                        <xs:attribute name="bookmark" type="xs:string" />
                    </xs:complexType>
                </xs:element>
                <xs:element name="pushFullArtScene">
                    <xs:complexType>
                        <xs:attribute name="art" type="art" use="required" />
                    </xs:complexType>
                </xs:element>
                <xs:element name="knownAction">
                    <xs:complexType>
                        <xs:attribute name="action" type="xs:string" />
                    </xs:complexType>
                </xs:element>
                <xs:element name="replaceHeldItem">
                    <xs:annotation>
                        <xs:documentation>
                            Replaces the currently held inventory item by a new item with the given art and description.
                        </xs:documentation>
                    </xs:annotation>
                    <xs:complexType>
                        <xs:attribute name="with" type="art" use="required">
                            <xs:annotation>
                                <xs:documentation>
                                    The name of the art of the new replacement item.
                                </xs:documentation>
                            </xs:annotation>
                        </xs:attribute>
                        <xs:attribute name="withDescription" type="xs:string" use="required" />
                    </xs:complexType>
                </xs:element>
            </xs:choice>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="character">
        <xs:restriction>
            <xs:enumeration value="Tišík" />
            <xs:enumeration value="Vědátor" />
            <xs:enumeration value="Vypravěč" />
            <xs:enumeration value="Lenka" />
            <xs:enumeration value="Smíšek" />
            <xs:enumeration value="Háthí" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="pose">
        <xs:restriction>
            <xs:enumeration value="thinking" />
            <xs:enumeration value="speaking" />
            <xs:enumeration value="excited" />
            <xs:enumeration value="pointing" />
            <xs:enumeration value="amused" />
            <xs:enumeration value="angry" />
            <xs:enumeration value="afraid" />
            <xs:enumeration value="normal" />
            <xs:enumeration value="shrugging" />
            <xs:enumeration value="determined" />
            <xs:enumeration value="blushing" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="nonEmptyString">
        <xs:restriction base="xs:string">
            <xs:minLength value="1" />
            <xs:pattern value="A.+" />
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== Soothsilver/NajdiCestuVen/Shared/Stories/Scenes/Prologue/Prologue.xml
<?xml version="1.0" encoding="utf-8"?>
<!--<scene>-->
<scene xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../scene.xsd">
    <enter>
        <pushScene name="Outside" />
    </enter>
    <scenes>
        <scene name="Outside">
            <backgrounds>
                <art>Overshot</art>
            </backgrounds>
            <enter>
                <s speaker="Tišík" pose="speaking">"Naší snahou nejlepší buď čin" je heslo vlčat.</s>
                <s speaker="Tišík" pose="thinking">Jak mi to vysvětloval Akela, tak znamená, že bych se měl snažit vždy co nejvíc dokážu.</s>
                <s speaker="Tišík" pose="speaking">Já - i ostatní vlčata a světlušky - se snažíme. </s>
                <s speaker="Tišík" pose="speaking">Ale Akela říkal, že tento víkend zažijeme dobrodružství, ve kterém se teprve ukáže, z čeho jsme.</s>
                <s speaker="Tišík" pose="determined">Podařilo se mu totiž pro nás zajistit víkend na zámku Duchov.</s>
                <zoomInto rectangle="888,96,1032,671" time="12" />
                <think>Zámek Duchov. Už za středověku byl opředený pověstmi a v moderní době byl sídlem přísně tajného vládního projektu.</think>
                <think>Také můj taťka byl výzkumníkem na tomto projektu.</think>
                <think>Ale před sedmi lety taťka {b}zmizel.{/b} Jednoho dne se z práce už nevrátil.</think>
                <think>Projekt byl ukončen, a zámek zapovězen.</think>
                <think>Ale dnes se vracíme! Já, Vědátor, Vypravěč, holky a Akela, budeme mít celý zámek jen sami pro sebe!</think>
                <think>Bude to dobrodružství, a... těším se! Ale taky se bojím.</think>
                <zoomInto rectangle="0,0,1920,1080" time="4" />
                <addBackgroundArt art="MainLogoCzech" />
                <think>Mám takové tušení, že tohle nebude úplně obvyklá skautská výprava...</think>
                <removeBackgroundArt art="MainLogoCzech" />
                <removeBackgroundArt art="Overshot" />
                <addBackgroundArt art="CourtyardDemo" />             
                <zoomInto rectangle="0,0,1920,1080" time="1" />
                <s speaker="Akela" pose="excited">Vlčata a světlušky! Vítejte na nádvoří zámku Duchov!</s>
                <s speaker="Vlčata a světlušky" pose="excited">Jupí!!!</s>
                <s speaker="Smíšek" pose="afraid">Já musím na záchod!</s>
                <s speaker="Lenka" pose="determined">Jestli jde Smíšek, tak já taky!</s>
                <s speaker="Akela" pose="pointing">Fajn, fajn. Záchody jsou tímto směrem.</s>
                <s speaker="Vypravěč" pose="pointing">Můžeme k jezírku?</s>
                <s speaker="Vědátor" pose="pointing">Oooh, tamhle je rytířské brnění!</s>
                <s speaker="Tišík" pose="pointing">Jdu se podívat do studny!</s>
                <s speaker="Akela" pose="angry">Tak počkejte chvilku, kluci! Žádný rozchod tady není.</s>
                <s speaker="Akela" pose="speaking">Já půjdu do hradu nahodit elektřinu, a vy na mě zatím počkejte ve strážnici.</s>
                <s speaker="Akela" pose="determined">Žádné jezírko, žádná studna, nikam nechoďte sami, jasný? Sedm let tu nikdo nebyl, všechno může být nebezpečné.</s>
                <s speaker="Tišík" pose="speaking">(zklamaně) Ano, Akelo.</s>
                <s speaker="Akela" pose="excited">Tak jděte, kluci. Za sedm minut jsem zpátky.</s>
                <removeBackgroundArt art="CourtyardDemo" />
                <addBackgroundArt art="Guardroom1" />
                <s speaker="Vědátor" pose="angry">Mno tahle místnost není tak zajímavá jako nádvoří.</s>
                <s speaker="Tišík" pose="speaking">Ale Akela bude za chvíli zpátky, a budeme moct prozkoumávat zámek.</s>
                <s speaker="Vědátor" pose="excited">Už se těším.</s>
                <s speaker="Tišík" pose="speaking">Nechceš si mezitím zahrát Bifröst?</s>
                <s speaker="Vědátor" pose="excited">Se ptáš? Balíček už mám zamíchaný!</s>
                <s speaker="Vypravěč" pose="angry">Bleh, zase Bifröst. Co vás na té hře baví?</s>
                <s speaker="Tišík" pose="speaking">Bifröst je nejlepší sběratelská karetní hra na světě! Tvůj balíček sestává z hrdinů, mytologických příšer a událostí--</s>
                <s speaker="Vypravěč" pose="shrugging">Stačí, stačí, zapomeňte, že jsem se ptal. Já už se nějak zabavím.</s>
                <think>-- o 30 minut později --</think>
                <s speaker="Tišík" pose="speaking">A nyní zahraju Mrazivé sítě, což posílí moje lukostřelce natolik, aby přemohli tvého draka?</s>
                <s speaker="Vědátor" pose="speaking">Aww, ubohý Nidhogg. Neboj, dráčku, příští kolo tě oživím z mrtvých.</s>
                <s speaker="Vypravěč" pose="thinking">Kluci, nemyslíte, že už sedm minut uplnynulo?</s>
                <s speaker="Vědátor" pose="thinking">...možná?</s>
                <s speaker="Tišík" pose="shrugging">Už jsem Vědátora porazil třikrát, takže asi jo. </s>
                <addBackgroundArt art="Guardroom1LockedGate" />
                <sfx name="PressureRelease"/>
                <sfx name="TrezorOpen"/>
                <s speaker="Tišík" pose="afraid">Haah?</s>
                <s speaker="Vědátor" pose="afraid">Co to bylo?!</s>
                <s speaker="Vypravěč" pose="pointing">Zavřely se dveře!</s>
                <s speaker="Tišík" pose="speaking">Není tu žádná klika.</s>
                <s speaker="Vědátor" pose="afraid">Jsme tady zavření?</s>
                <s speaker="Tišík" pose="speaking">Něco muselo zavřít ty dveře! </s>
                <s speaker="Vědátor" pose="afraid">Možná to byl duch?</s>
                <s speaker="Tišík" pose="speaking">Duch?</s>
                <s speaker="Vědátor" pose="shrugging">Mno, podle něčeho se ten zámek jmenuje Duchov, ne?</s>
                <s speaker="Vědátor" pose="afraid">...</s>
                <s speaker="Vědátor" pose="afraid">Já... se bojím, kluci.</s>
                <s speaker="Tišík" pose="speaking">Já taky, ale --</s>
                <s speaker="Tišík" pose="determined">Ale zvládneme to. Jsme vlčata. Zjistíme, co se tady děje.</s>
                <s speaker="Vypravěč" pose="determined">Jako první bychom se asi měli vrátit nějak na nádvoří.</s>
                <s speaker="Tišík" pose="determined">Ano, prohledejme místnost.</s>
                <s speaker="Tišík" pose="thinking">Někde tu musí být něco, co nás dostane ven.</s>
                <popScene/>
                <popScene/>
                <enqueue bookmark="R1_Guardhouse_Xml_Level" />
            </enter>
        </scene>
    </scenes>
</scene>

=== Soothsilver/NajdiCestuVen/Shared/Stories/Scenes/Prison/LieDetector.xml
<?xml version="1.0" encoding="utf-8"?>
<scene xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../scene.xsd">
    <backgrounds>
        <art>R1_Table</art>
    </backgrounds>
    <enter>
        <s speaker="Háthí" pose="speaking">Já jsem Háthí, hlavní automatická inteligence projektu Džungle.</s>
        <s speaker="Tišík" pose="pointing">Ozývá se to z toho detektoru!</s>
        <s speaker="Háthí">Test pravdomluvnosti právě začíná, přízraku. Po jeho splnění ti bude povoleno odejít.</s>
        <s speaker="Háthí">Posaď se a připoj na svoje tělo elektrody podle návodu.</s>
        <s speaker="Vědátor" pose="afraid">Máme udělat, co říká?</s>
        <s speaker="Tišík" pose="thinking">Nenapadá mě nic jiného. Jiná cesta ven nevede.</s>
        <s speaker="Vypravěč" pose="speaking">Nějaký dobrovolník?</s>
        <s speaker="Tišík" pose="determined">Já půjdu. Připojte to na mě.</s>
        <s speaker="Vypravěč" pose="shrugging">Když myslíš, Tišíku.</s>
        <s speaker="Vědátor" pose="afraid">Hodně štěstí.</s>
        <pushFullArtScene art="LieDetector1"/>
        <s speaker="Háthí">Zapojeno. Účelem tohoto testu je zjistit, zda dokážeš rozeznat pravdu od lži, a ctít pravdu.</s>
        <s speaker="Háthí">Na všechny následující otázky odpověz pravdivě podle svého nejlepšího svědomí.</s>
        <s speaker="Háthí">Jak se jmenuješ?</s>
        <pushFullArtScene art="LieDetectorSpeaking"/>
        <s speaker="Tišík">Jsem Honza Kamenický, na skautu mi říkají Tišík.</s>
        <pushFullArtScene art="LieDetector1"/>
        <sfx name="LieOk" />
        <s speaker="Háthí">Pravda. Už jsi někoho zabil?</s>
        <pushFullArtScene art="LieDetectorSpeaking"/>
        <s speaker="Tišík">Ne.</s>
        <pushFullArtScene art="LieDetector1"/>
        <sfx name="LieOk" />
        <s speaker="Háthí">Pravda. Už jsi někdy kradl?</s>
        <pushFullArtScene art="LieDetectorSpeaking"/>
        <s speaker="Tišík">Ne.</s>
        <pushFullArtScene art="LieDetectorShock"/>
        <sfx name="LieShock" />
        <sfx name="AccessDenied" />
        <s speaker="Tišík">Aaaahhh.</s>
        <s speaker="Vědátor" pose="afraid">Tišíku! </s>
        <s speaker="Vypravěč" pose="speaking">Jsi v pořádku?</s>
        <pushFullArtScene art="LieDetectorSpeaking"/>
        <s speaker="Tišík">Wow, je to... fakt jako ve filmu...</s>
        <pushFullArtScene art="LieDetector1"/>
        <s speaker="Vědátor" pose="pointing">Ten detektor dává elektrické šoky, když zalžeš!</s>
        <s speaker="Vypravěč" pose="determined">Musíme si na tenhle zámek dávat pozor.</s>
        <pushFullArtScene art="LieDetectorSpeaking"/>
        <s speaker="Tišík">Dobrý, kluci, myslím, že to zvládnu.</s>
        <pushFullArtScene art="LieDetector1"/>
        <s speaker="Háthí">Připomínám, přízraku, že musíš odpovědět pravdivě. Opakuji otázku: Už jsi někdy kradl?</s>
        <pushFullArtScene art="LieDetectorSpeaking"/>
        <s speaker="Tišík">Ano.</s>
        <pushFullArtScene art="LieDetector1"/>
        <sfx name="LieOk" />
        <s speaker="Vědátor" pose="thinking">Vážně jsi něco kradl, Tišíku?</s>
        <s speaker="Vědátor" pose="speaking">Byly to počítačové hry? Protože to se nepočítá.</s>
        <s speaker="Vypravěč" pose="angry">Crackování počítačových her je krádež jako každá jiná.</s>
        <s speaker="Vědátor" pose="angry">To teda není. Je to digitální, a je jich nekonečno, takže se to nepočítá.</s>
        <s speaker="Vypravěč" pose="pointing">A řekl bys to vývojářům do tváře?</s>
        <s speaker="Vypravěč" pose="determined">"Ahoj, vývojáři. Já jsem Vědátor. Tvoje hra se mi líbí, ale nechci za ní platit. Tak jsem si jí stáhnul. Jsme v poho, že?"</s>
        <s speaker="Vědátor" pose="thinking">Mno...</s>
        <s speaker="Vypravěč" pose="pointing">Kdyby tady byl vývojář Najdi cestu ven!, tak by ti to taky řekl.</s>
        <s speaker="Vypravěč" pose="thinking">I když tahle hra je freeware, takže za ní nemusí platit nikdo. Hmm...</s>
        <s speaker="Háthí">Komu jsi něco ukradl?</s>
        <pushFullArtScene art="LieDetectorSpeaking"/>
        <s speaker="Tišík">Já... uh....</s>
        <pushFullArtScene art="LieDetector1"/>
        <s speaker="Vědátor" pose="determined">Nám můžeš říct cokoliv. Neboj se mluvit pravdu.</s>
        <pushFullArtScene art="LieDetectorSpeaking"/>
        <s speaker="Tišík">Vědátorovi.</s>
        <pushFullArtScene art="LieDetector1"/>
        <s speaker="Vědátor" pose="thinking">Mně? Ale... co?</s>
        <sfx name="LieOk" />
        <s speaker="Háthí">Pravda. Co jsi ukradl?</s>
        <pushFullArtScene art="LieDetectorSpeaking"/>
        <s speaker="Tišík">Já... to nemůžu říct.</s>
        <pushFullArtScene art="LieDetectorShock"/>
        <sfx name="LieShock" />
        <sfx name="AccessDenied" />
        <s speaker="Tišík">Aah!</s>
        <s speaker="Vypravěč" pose="afraid">Tišíku!</s>
        <s speaker="Vědátor" pose="afraid">Neboj, ať je to cokoliv, já ti odpouštím!</s>
        <s speaker="Vypravěč" pose="determined">A potom tenhle krutý detektor zničíme, ať je to cenný výtvor lidský nebo ne!</s>
        <pushFullArtScene art="LieDetectorSpeaking"/>
        <s speaker="Tišík">Vědátore, pamatuješ, jak jsi ztratil Himiko?</s>
        <pushFullArtScene art="LieDetector1"/>
        <s speaker="Vědátor" pose="excited">Himiko v oáze, kartu hlavní hrdinky z edice, kdy se příběh přesunul z mrazivého severu do tropů?</s>
        <pushFullArtScene art="LieDetectorSpeaking"/>
        <s speaker="Tišík">Ano... ve skutečnosti jsi jí neztratil.</s>
        <sfx name="LieOk" />
        <s speaker="Háthí">Pravda.</s>
        <s speaker="Vědátor" pose="thinking">Tys mi jí vzal? Ta karta ani není nijak vzácná. Samozřejmě že ti odpouštím.</s>
        <s speaker="Háthí">Mluvit pravdu je první krok k dobrému životu, přízraku.</s>
        <pushFullArtScene art="Guardroom1"/>
        <sfx name="LieOk" />
        <sfx name="PressureRelease" />
        <s speaker="Háthí">Prošel jsi testem pravdomluvnosti. Odemykám dveře.</s>
        <s speaker="Vypravěč" pose="excited">Jo!</s>
        <s speaker="Vypravěč" pose="pointing">Rychle, ven, na nádvoří!</s>
        <s speaker="Vědátor" pose="thinking">Ale, Tišíku, proč jsi chtěl tu kartu? Není ani silná.</s>
        <s speaker="Tišík" pose="blushing">Já... uh... no... </s>
        <s speaker="Vypravěč" pose="pointing">...musíme na nádvoří!</s>
        <pushFullArtScene art="CourtyardDemo"/>
        <s speaker="Smíšek" pose="excited">Kluci!</s>
        <s speaker="Lenka" pose="excited">Jste v pořádku!</s>
        <s speaker="Vypravěč" pose="thinking">Kde je Akela?</s>
        <s speaker="Lenka" pose="shrugging">To jsme se chtěli zeptat my.</s>
        <s speaker="Smíšek" pose="speaking">Všechny brány z nádvoří jsou zamčené. Dovnitř i ven.</s>
        <s speaker="Vědátor" pose="thinking">Záchod je stále odemčený?</s>
        <s speaker="Smíšek" pose="shrugging">To ano, ale ---</s>
        <s speaker="Vědátor" pose="afraid">Tedy mě omluvte!</s>
        <s speaker="Vypravěč" pose="afraid">Já taky musím!</s>
        <s speaker="Lenka" pose="angry">Jo, to vám je podobný. Utíkáte, jen co je třeba pracovat.</s>
        <s speaker="Tišík" pose="thinking">Nebe vypadá dost strašidelně. </s>
        <s speaker="Smíšek" pose="speaking">Jo no. Brzy se spustí dost silná bouřka.</s>
        <s speaker="Tišík" pose="determined">Nemůžeme čekat, až se kluci vrátí ze záchoda. Musíme najít Akelu dřív, než začne pršet!</s>
        <popAllScenes />
        <enqueue bookmark="R2_Courtyard" />
    </enter>
</scene>
